# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-16 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='CombineType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ConnectorCable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loss_rate', models.FloatField()),
                ('outer_diameter', models.FloatField()),
                ('inner_diameter', models.FloatField()),
                ('cable_type', models.CharField(max_length=30)),
                ('upper_frequency', models.FloatField()),
                ('property', models.CharField(max_length=30)),
                ('document', models.FileField(upload_to='connectorCable/')),
                ('full_witc', models.CharField(max_length=30)),
                ('combo_short_witc', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='connectorCable/')),
                ('comments', models.CharField(max_length=100)),
                ('reserved1', models.CharField(max_length=100)),
                ('reserved2', models.CharField(max_length=100)),
                ('combine_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page_example.CombineType')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page_example.Category')),
            ],
        ),
        migrations.CreateModel(
            name='ConnectorPcb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standing_wave', models.FloatField()),
                ('upper_frequency', models.FloatField()),
                ('property', models.CharField(max_length=30)),
                ('document', models.FileField(upload_to='connectorCable/')),
                ('image', models.ImageField(upload_to='connectorCable/')),
                ('comments', models.CharField(max_length=100)),
                ('reserved1', models.CharField(max_length=100)),
                ('reserved2', models.CharField(max_length=100)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page_example.Category')),
            ],
        ),
        migrations.CreateModel(
            name='InstallType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OutLook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Polar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='connectorpcb',
            name='install_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page_example.InstallType'),
        ),
        migrations.AddField(
            model_name='connectorpcb',
            name='outlook_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page_example.OutLook'),
        ),
        migrations.AddField(
            model_name='connectorpcb',
            name='polar_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page_example.Polar'),
        ),
        migrations.AddField(
            model_name='connectorcable',
            name='install_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page_example.InstallType'),
        ),
        migrations.AddField(
            model_name='connectorcable',
            name='outlook_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page_example.OutLook'),
        ),
        migrations.AddField(
            model_name='connectorcable',
            name='polar_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page_example.Polar'),
        ),
    ]
