# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-21 04:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page_example', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Converter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standing_wave', models.FloatField()),
                ('upper_frequency', models.FloatField()),
                ('full_witc', models.CharField(max_length=30)),
                ('document', models.FileField(upload_to='converter/')),
                ('image', models.ImageField(upload_to='converter/')),
                ('comments', models.CharField(max_length=100)),
                ('reserved1', models.CharField(max_length=100)),
                ('reserved2', models.CharField(max_length=100)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('a_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a_category', to='page_example.Category')),
                ('a_polar_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='a_polar', to='page_example.Polar')),
                ('b_content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b_category', to='page_example.Category')),
                ('b_polar_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='b_polar', to='page_example.Polar')),
                ('install_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page_example.InstallType')),
                ('outlook_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page_example.OutLook')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page_example.Property')),
            ],
        ),
    ]
