# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-21 04:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('page_example', '0002_converter'),
    ]

    operations = [
        migrations.AddField(
            model_name='converter',
            name='material',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
    ]
