# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 13:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('page_example', '0003_auto_20171218_1104'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectorpcb',
            name='combo_short_witc',
            field=models.CharField(default=django.utils.timezone.now, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='connectorpcb',
            name='full_witc',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
