# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-21 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('page_example', '0004_auto_20171221_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='cable',
            name='document',
            field=models.FileField(default=django.utils.timezone.now, upload_to='cable/'),
            preserve_default=False,
        ),
    ]
