# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-12-21 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('page_example', '0005_cable_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='cable',
            name='full_witc',
            field=models.CharField(default=django.utils.timezone.now, max_length=30),
            preserve_default=False,
        ),
    ]
