# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 12:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page_example', '0006_cable_full_witc'),
    ]

    operations = [
        migrations.CreateModel(
            name='VNAComboCable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a_content_type', models.CharField(max_length=30)),
                ('b_content_type', models.CharField(max_length=30)),
                ('cable_length', models.FloatField()),
                ('full_witc', models.CharField(max_length=30)),
                ('document', models.FileField(upload_to='vna_combo_cable/')),
                ('image', models.ImageField(upload_to='vna_combo_cable/')),
                ('comments', models.CharField(max_length=100)),
                ('reserved1', models.CharField(max_length=100)),
                ('reserved2', models.CharField(max_length=100)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('a_polar_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vna_a_polar', to='page_example.Polar')),
                ('b_polar_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vna_b_polar', to='page_example.Polar')),
            ],
        ),
    ]
