# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-23 08:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_example', '0008_frequencypoint_frequencystandingwave'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequencypoint',
            name='comments',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='frequencypoint',
            name='reserved1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='frequencypoint',
            name='reserved2',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
