# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-24 07:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('page_example', '0009_auto_20171223_0810'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('full_witc', models.CharField(max_length=30)),
                ('document', models.FileField(upload_to='others/')),
                ('image', models.ImageField(upload_to='others/')),
                ('comments', models.CharField(max_length=100)),
                ('reserved1', models.CharField(max_length=100)),
                ('reserved2', models.CharField(max_length=100)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OtherProductType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=30)),
                ('code', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='otherproduct',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='page_example.OtherProductType'),
        ),
    ]
