# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-24 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_example', '0010_auto_20171224_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frequencystandingwave',
            name='standing_wave',
            field=models.FloatField(default=0.0),
        ),
    ]
