# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-27 14:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_example', '0012_recentproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recentproduct',
            name='description',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='recentproduct',
            name='property',
            field=models.CharField(max_length=100),
        ),
    ]
