# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-28 15:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page_example', '0014_auto_20180327_1453'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cable',
            name='id',
        ),
        migrations.RemoveField(
            model_name='connectorpcb',
            name='id',
        ),
        migrations.RemoveField(
            model_name='converter',
            name='id',
        ),
        migrations.RemoveField(
            model_name='otherproduct',
            name='id',
        ),
        migrations.RemoveField(
            model_name='recentproduct',
            name='id',
        ),
        migrations.RemoveField(
            model_name='vnacombocable',
            name='id',
        ),
        migrations.AlterField(
            model_name='cable',
            name='full_witc',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='connectorpcb',
            name='full_witc',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='converter',
            name='full_witc',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='otherproduct',
            name='full_witc',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='recentproduct',
            name='full_witc',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vnacombocable',
            name='full_witc',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
