# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-03-29 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('page_example', '0015_auto_20180328_1555'),
    ]

    operations = [
        migrations.AddField(
            model_name='recentproduct',
            name='r_witc',
            field=models.CharField(default=django.utils.timezone.now, max_length=30, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='recentproduct',
            name='full_witc',
            field=models.CharField(max_length=30),
        ),
    ]
